import type { CmsData } from "./types";

export const defaultCmsData: CmsData = {
  site: {
    heroEyebrow: "Private Musikakademie · Hamburg-Altona · Seit 1987",
    heroTitleLine1: "Alfred Schnittke",
    heroTitleAccent: "Akademie",
    heroTitleLine2: "International",
    heroSubtitle:
      "Wo zeitgenössische Musik auf Tradition trifft – Studium, Konzerte und Meisterkurse in einer hanseatischen Villa",
    aboutKicker: "Über die Akademie",
    aboutTitleLine1: "Musik studieren",
    aboutTitleAccent: "unter einem neuen Akzent",
    aboutLead:
      "Die Alfred Schnittke Akademie International ist eine von der Kulturbehörde anerkannte private Musikakademie in Hamburg-Altona. Seit 1987 bilden wir junge Musiker in Gesang und Instrumentalspiel aus – mit dem Schwerpunkt auf zeitgenössischer Musik und einem individuellen Studienplan für jeden Studierenden.",
  },
  events: [
    {
      id: "event-1",
      date: "15. März 2026",
      time: "19:30 Uhr",
      title: "Schnittke: Streichquartett Nr. 3",
      category: "Konzert",
      location: "Konzertsaal",
      description: "Ein Konzertabend mit Werken von Alfred Schnittke und Zeitgenossen.",
      seatsLabel: "42 Plätze frei",
      color: "#7A0000",
      status: "published",
      ticketEnabled: true,
    },
    {
      id: "event-2",
      date: "22. März 2026",
      time: "10:00 Uhr",
      title: "Meisterkurs Violine mit Prof. Kopatchinskaja",
      category: "Meisterkurs",
      location: "Kammermusikraum",
      description: "Öffentlicher Meisterkurs für fortgeschrittene Studierende.",
      seatsLabel: "8 Plätze frei",
      color: "#D00000",
      status: "published",
      ticketEnabled: true,
    },
    {
      id: "event-3",
      date: "05. April 2026",
      time: "19:00 Uhr",
      title: "Viktor Shenderovich – Lesung",
      category: "Lesung",
      location: "Historische Villa",
      description: "Literarischer Abend im Rahmen des Kulturprogramms.",
      seatsLabel: "35 Plätze frei",
      color: "#0A0A0A",
      status: "published",
      ticketEnabled: true,
    },
    {
      id: "event-4",
      date: "18. April 2026",
      time: "18:00 Uhr",
      title: "Polystilistik – Workshop für junge Komponisten",
      category: "Workshop",
      location: "Seminarraum",
      description: "Workshop zu Stilpluralismus und zeitgenössischer Komposition.",
      seatsLabel: "12 Plätze frei",
      color: "#262626",
      status: "published",
      ticketEnabled: true,
    },
  ],
  posts: [
    {
      id: "post-1",
      title: "Neue Meisterkurse im Frühjahr",
      slug: "neue-meisterkurse-im-fruehjahr",
      category: "Akademie",
      excerpt:
        "Die Akademie erweitert ihr Kursprogramm um neue Formate für Kammermusik, Violine und zeitgenössische Komposition.",
      body:
        "Im Frühjahr bietet die Alfred Schnittke Akademie International zusätzliche Meisterkurse für junge Musikerinnen und Musiker an. Details zu Terminen, Dozenten und Teilnahmebedingungen folgen in Kürze.",
      imageUrl: "",
      imageAlt: "",
      publishedAt: "2026-03-01",
      status: "published",
    },
  ],
  tickets: [],
  updatedAt: new Date().toISOString(),
};
